rd /S /Q .vs
rd /S /Q ..\..\appDX11ShaderCompiler\bin
rd /S /Q ..\..\appDX11ShaderCompiler\exe
rd /S /Q ..\..\appImmUnity\bin
rd /S /Q ..\..\appImmUnity\exe
rd /S /Q ..\..\appImmViewer\bin
del /S /Q ..\..\appImmViewer\exe\appImmViewer_Debug.*
del /S /Q ..\..\appImmViewer\exe\appImmViewer_Release.*
del /S /Q ..\..\appImmViewer\exe\debug.txt
rd /S /Q ..\..\libImmCore\bin
rd /S /Q ..\..\libImmExporter\bin
rd /S /Q ..\..\libImmImporter\bin
rd /S /Q ..\..\libImmPlayer\bin